name: Salesforce Deployment and Testing

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Salesforce CLI
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Salesforce CLI
      run: npm install sfdx-cli --global

    - name: Authenticate Salesforce Org
      run: |
        echo ${{ secrets.SFDX_AUTH_URL }} > authUrlFile
        sfdx force:auth:sfdxurl:store -f authUrlFile -a CycloneSolutions

    - name: Deploy to Salesforce Org
      run: sfdx force:source:deploy --sourcepath force-app/main/default --wait 10 --json -u CycloneSolutions

    - name: Run Apex Tests
      run: sfdx force:apex:test:run --wait 10 --json -u CycloneSolutions